# -*- coding: utf-8 -*-
"""Ejercicio2_Tarea3_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PWsnCRFubdDBetZJq8dn4iTe-e6YlogF
"""

import numpy as np

def eliminacion_gaussiana(matriz, vector):
    matriz = matriz.copy()  # Crear copia para evitar modificar la original
    vector = vector.copy()  # Copia del vector independiente
    n = len(vector)  # Número de ecuaciones

    for i in range(n):
        # Selección de pivote (pivoteo parcial)
        fila_max = i + np.argmax(np.abs(matriz[i:, i]))
        if fila_max != i:
            matriz[[i, fila_max], :] = matriz[[fila_max, i], :].copy()  # Intercambio de filas
            vector[[i, fila_max]] = vector[[fila_max, i]].copy()

        # Eliminación progresiva
        for j in range(i + 1, n):
            factor = matriz[j, i] / matriz[i, i]
            matriz[j, i:] -= factor * matriz[i, i:]
            vector[j] -= factor * vector[i]

    # Sustitución regresiva para encontrar la solución
    solucion = np.zeros(n)
    for i in range(n - 1, -1, -1):
        solucion[i] = (vector[i] - np.dot(matriz[i, i + 1:], solucion[i + 1:])) / matriz[i, i]

    return solucion

# Definir una matriz de coeficientes 5x5 y un vector de términos independientes
matriz_coef = np.array([
    [6, -2, 3, -1, 2],
    [-3, 5, -2, 4, -1],
    [4, 3, 7, -5, 3],
    [-2, 6, -3, 1, -4],
    [1, -3, 2, -5, 6]
], dtype=float)

vector_indep = np.array([15, -6, 20, -4, 7], dtype=float)

# Resolver el sistema de ecuaciones
solucion = eliminacion_gaussiana(matriz_coef, vector_indep)

# Mostrar la solución
print("Solución del sistema:")
print(solucion)